export const ADD_DOCTOR = "ADD_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";

export const ADD_SURGERY_TYPE = "ADD_SURGERY_TYPE";
export const DELETE_SURGERY_TYPE = "DELETE_SURGERY_TYPE";
export const UPDATE_SURGERY_TYPE = "UPDATE_SURGERY_TYPE";

export const ADD_SICK = "ADD_SICK";
export const DELETE_SICK = "DELETE_SICK";
export const UPDATE_SICK = "UPDATE_SICK";

export const SET_TYPE_OF_WORK = "SET_TYPE_OF_WORK";


export const ADD_EXPENSE_TYPE = "ADD_EXPENSE_TYPE";
export const DELETE_EXPENSE_TYPE = "DELETE_EXPENSE_TYPE";
export const UPDATE_EXPENSE_TYPE = "UPDATE_EXPENSE_TYPE";

export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";

export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";