export const DELETE_DOCTOR = "DELETE_DOCTOR";
export const DELETE_SURGERY_TYPE = "DELETE_SURGERY_TYPE";
export const DELETE_SICK = "DELETE_SICK";
export const DELETE_EXPENSE_TYPE = "DELETE_EXPENSE_TYPE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const DELETE_USER = "DELETE_USER";
